name: tekartik_build_menu_flutter
description: Build menu flutter
version: 0.4.0
publish_to: none

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  path: ">=1.9.0"
  dev_build: ">=1.1.0+2"
  process_run: ">=1.2.1+1"
  args: ">=2.6.0"
  tekartik_build_flutter:
    git:
      url: https://github.com/tekartik/build_flutter.dart
      ref: dart3a
      path: packages/build_flutter
    version: '>=1.0.2'
  uuid: '>=3.0.0-0'
  tekartik_built_flutter:
    git:
      url: https://github.com/tekartik/build_flutter.dart
      ref: dart3a
      path: packages/built_flutter
    version: '>=0.1.0'
  tekartik_app_args:
    git:
      url: https://github.com/tekartik/app_io_utils.dart
      ref: dart3a
      path: packages/app_args
    version: '>=0.1.0'
  tekartik_android_utils:
    git:
      url: https://github.com/tekartik/android_utils.dart
      ref: dart3a
  tekartik_appstore_publish:
    git:
      url: https://github.com/tekartik/app_build.dart
      ref: dart3a
      path: packages/appstore_publish

dev_dependencies:
  lints: ">=5.0.0"
  test: ">=1.24.0"

executables:
  fbm: fbm
