name: tekartik_build_menu_flutter
description: Build menu flutter
version: 0.3.0
publish_to: none

environment:
  sdk: '>=2.16.0-0 <3.0.0'

dependencies:
  tekartik_build_flutter:
    git:
      url: https://github.com/tekartik/build_flutter.dart
      ref: dart2_3
      path: packages/build_flutter
    version: '>=0.7.9'
  uuid: '>=3.0.0-0'
  tekartik_test_menu_io:
    git:
      url: https://github.com/tekartik/test_menu.dart
      ref: dart2_3
      path: test_menu_io

dependency_overrides:
  tekartik_build_flutter:
    path: ../build_flutter

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
