name: tekartik_build_menu_flutter
description: Build menu flutter
version: 0.3.4
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  path:
  dev_test: '>=0.16.2+3'
  process_run:
  args:
  tekartik_build_flutter:
    git:
      url: https://github.com/tekartik/build_flutter.dart
      ref: dart3a
      path: packages/build_flutter
    version: '>=1.0.2'
  uuid: '>=3.0.0-0'
  tekartik_test_menu_io:
    git:
      url: https://github.com/tekartik/test_menu.dart
      ref: dart3a
      path: test_menu_io
  tekartik_test_menu:
    git:
      url: https://github.com/tekartik/test_menu.dart
      ref: dart3a
      path: test_menu
  tekartik_built_flutter:
    git:
      url: https://github.com/tekartik/build_flutter.dart
      ref: dart3a
      path: packages/built_flutter
    version: '>=0.1.0'
  tekartik_app_args:
    git:
      url: https://github.com/tekartik/app_io_utils.dart
      ref: dart3a
      path: packages/app_args
    version: '>=0.1.0'
dependency_overrides:
  tekartik_build_flutter:
    path: ../build_flutter
  tekartik_built_flutter:
    path: ../built_flutter

dev_dependencies:
  lints: '>=1.0.0'
  test: '>=1.16.0'

executables:
  fbm: fbm
