name: tekartik_built_flutter
description: Constants for project build with build_flutter.
version: 0.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

resolution: workspace
# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: '>=2.0.0'
  test: '>=1.21.0'
