name: tekartik_build_flutter
description: Helper for building flutter project
version: 1.0.4
publish_to: none

environment:
  sdk: '>=2.14.4 <3.0.0'

dependencies:
  path: ^1.8.0
  process_run:
  fs_shim:
  collection:
  args:
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart2_3
    version: '>=0.13.2'
  dev_test:
  tekartik_android_utils:
    git:
      url: https://github.com/tekartik/android_utils.dart
      ref: dart2_3
    version: '>=0.1.0'
  tekartik_app_io_platform:
    git:
      url: https://github.com/tekartik/app_io_utils.dart
      ref: dart2_3
      path: packages/app_platform
    version: '>=0.3.1'
dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0

