name: tekartik_build_flutter
description: Helper for building flutter project
version: 1.0.5
publish_to: none

environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  cv: ">=1.1.0+4"
  path: ">=1.9.0"
  process_run: ">=1.2.1+1"
  fs_shim: ">=2.3.3+1"
  collection: ">=1.18.0"
  args: ">=2.6.0"
  tekartik_lints_flutter:
    git:
      url: https://github.com/tekartik/common_flutter.dart
      path: packages/lints_flutter
    version: '>=0.1.0'
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
    version: '>=0.13.2'
  dev_build: ">=1.1.2"
  tekartik_android_utils:
    git:
      url: https://github.com/tekartik/android_utils.dart
    version: '>=0.1.0'
  tekartik_app_io_platform:
    git:
      url: https://github.com/tekartik/app_io_utils.dart
      path: packages/app_platform
    version: '>=0.3.1'
  tekartik_built_flutter:
    git:
      url: https://github.com/tekartik/build_flutter.dart
      path: packages/built_flutter
    version: '>=0.1.0'
  tekartik_playstore_publish:
    git:
      url: https://github.com/tekartik/app_build.dart
      path: packages/playstore_publish
  tekartik_common_build:
    git:
      url: https://github.com/tekartik/app_build.dart
      path: packages/common_build

dev_dependencies:
  lints: ">=5.0.0"
  test: ">=1.24.0"
