name: tekartik_build_flutter
description: Helper for building flutter project
version: 1.0.3
publish_to: none

environment:
  sdk: '>=2.14.4 <3.0.0'

dependencies:
  path: ^1.8.0
  process_run:
  args:
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart2_3
    version: '>=0.13.2'
  dev_test:
dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0

