name: app_build_menu_example_support
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.7.0


dependencies:
  path: ">=1.9.0"
  tekartik_build_menu_flutter:
    git:
      url: https://github.com/tekartik/build_flutter.dart
      ref: dart3a
      path: packages/build_menu_flutter
    version: '>=0.1.0'

dependency_overrides:
  tekartik_build_menu_flutter:
    path: ../../packages/build_menu_flutter
  tekartik_build_flutter:
    path: ../../packages/build_flutter

dev_dependencies:
  lints: ">=5.0.0"
  test: ">=1.24.0"
