name: build_flutter_repo_support
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.9.0

resolution: workspace
dependencies:
  dev_build: ">=1.1.2"
  process_run: ">=1.2.1+1"
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
    version: '>=0.13.2'
  path: ">=1.9.0"
  tekartik_build_menu_flutter:
    git:
      url: https://github.com/tekartik/build_flutter.dart
      path: packages/build_menu_flutter
dev_dependencies:
  test: ">=1.24.0"

dependency_overrides:
#  tekartik_build_utils:
#    path: ../../../tekartik/build_utils.dart
